version: "3.7"
services:
  localstack:
    image: localstack/localstack:0.9.4
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
  initialize_queues:
    build: .
    command: ["python3", "initialize_queues.py"]
    depends_on:
      - localstack
    links:
      - localstack